Personas
Requisitos-de-Software/2022.2-GoogleMaps pull request #27
Opened 2022-11-25 12:41 UTC by lucasfs1007

- adiciona pérfil de usuários
 - adiciona tabela de 2 personas e uma antipersona
 - adiciona atualização de bibliografia e versionamento
 - Aguardo sugestão para melhorias 
 - closes #22 #24

2022-11-27 21:34 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +&emsp;&emsp;Os membros, Lucas Felipe e Luciano Freitas foram os responsaveis por criar personas que retratariam os usuarios mais comuns do Google Maps. A partir desses requisitos e da pesquisa de gru
Acho que seria interessante construir o texto de maneira impessoal.

2022-11-27 21:38 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +<p>Tabela 1: Persona 1</p>
Essa deveria ser a tabela 2. Também é importante que se padronize onde fica a descrição da tabela, na anterior está embaixo da tabela e nas próximas anterior à tabela.

2022-11-27 21:43 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Foto**            | <img width="200px" src="/assets/personas/persona1.jpg"><p>Figura 1 Manuel Persona</p>
Na tag p, das figuras 1 e 2, falta uma vírgula assim como existe nas figuras 3 e 4.

2022-11-27 21:45 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Descrição**       | Manuel Gomes, idade de 54 anos, morador de Ribeirão Preto.<br> Motorista de aplicativo.<br>Homem. <br>Divorciado,sem filhos. <br>Mora no centro da cidade, Ribeirão Preto.
Faltou o espaço depois da vírgula em "Divorciado,sem filhos".

2022-11-27 21:49 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Manuel nunca se deu muito bem com as novas tecnologias, e apesar de ser um grande motorista ainda passa por grandes dificuldades para se encontrar os melhores trajetos para su
Em "`[...] tecnologias, e apesar de ser um grande motorista ainda [...]`", a parte "apesar de ser um grande motorista" é um aposto. Portanto, corrigindo ficaria "`[...] tecnologias e, apesar de ser um grande motorista, ainda [...]`".

2022-11-27 21:52 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Juliana sempre foi uma pessoa muita ativa e focada em seu serviço, dévido sua devoção ao trabalho basicamente cumpre sempre a mesma rota do hospital para casa. Buscando ao máx
Remover o acento agudo no "`é`" em "`dévido`".
Também seria interessante remover o "`basicamente`", já que não exerce função nenhuma na frase.

2022-11-27 22:10 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Habilidades**     | Juliana tem como suas principais habilidades, a empatia por seus pacientes, sua devoção e entrega ao trabalho e ser uma pessoa extremamente discreta e precisa em seus objetivo
- Em "`[...] habilidades, a empatia [...]`", seria bom tirar a vírgula ou substituir por "dois pontos" ( : ) .

- Em "`[...] sua devoção e entrega ao [...]`", "devoção" e "entrega" tem sentidos iguais, acho válido escolher um dos dois, de preferência "devoção".

- Essa última troca também é importante para evitar a repetição do `e` que ocorre novamente em "`[...] trabalho e ser [...]`" e "`[...] discreta e precisa [...]`".

2022-11-27 22:14 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Tarefas**         | Todos os dias, Juliana repete sua mesma rota de casa para o trabalho. Procurando ao máximo não desviar muito de sua rotina padrão. Para Juliana suas atividades devem ser quase
Em "`[...] repete sua mesma rota [...]`", seria bom trocar "`sua mesma`" por:

- "`a mesma`"
**OU**
- apenas "`sua`".

2022-11-27 22:16 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Requisitos**      | Devido pouca variação em suas rotas, Juliana não enxerga nenhuma necessidade de se utilizar o Google Maps.
Corrigir início para: "`Devido a pouca [...]`".

2022-11-27 22:18 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Descrição**       | Carolina SIlveira, idade de 46 anos, moradora de Goiânia.<br> Servidora Pública.<br>Mulher. <br>casada,sem filhos. <br>Mora na zona sul da cidade, afastada de seu emprego.
Na persona _Juliana_ é explicitado o estado, mas nas outras apenas a cidade, padronizar isso.

2022-11-27 22:46 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Descrição**       | Ricardo Mendes, idade de 50 anos, morador de Curitiba.<br> Desenvolvedor de Software.<br>Homem. <br>casado, sem filhos. <br>Mora na zona central da cidade.
Colocar "`casado`" iniciando com letra maiúscula.

2022-11-27 22:48 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Ricardo Mendes, mudou-se recentemente para a cidade de Curitiba(PR). Gosta de utilizar o aplicativo para melhor se situar nas possibilidades de rota de sua nova cidade, nas av
Em "`[...] locais que se deseja conhecer [...]`", creio que o uso do "`se`" não se aplica.

2022-11-27 22:49 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Carolina Silveira, por morar muito afastada de seu emprego e com muito pouco senso de direção, busca formas diferentes de se chegar a tempo em seu trabalho e na sua rota para
Em "[...] diferentes de se chegar a [...]", não tenho certeza sobre o uso do "`se`" ser correto, recomendo remover para evitar erros.

2022-11-27 22:51 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Requisitos**      | Ricardo, espera que ao acessar o aplicativo do Google Maps possa aprender cada vez mais sobre a cidade de Curitiba.
Uso incorreto da vírgula.

2022-11-27 22:53 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +|        |
Cuidado para não deixar uma linha a mais na tabela quando finalizar as correções.

2022-11-27 22:54 UTC, marcusmartinss requested changes
Existem algumas anotações no código em relação à gramatica e correções pontuais.

2022-11-27 23:46 UTC, luciano-freitas-melo commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Juliana sempre foi uma pessoa muita ativa e focada em seu serviço, dévido sua devoção ao trabalho basicamente cumpre sempre a mesma rota do hospital para casa. Buscando ao máx
O "`a`" não tem crase, pois "`sua`" não é substantivo.
Alterei um pouco a frase, por favor revisar o que foi alterado!

2022-11-27 23:55 UTC, luciano-freitas-melo commented on docs/elicitacao/personas.md
> +| **Descrição**       | Carolina SIlveira, idade de 46 anos, moradora de Goiânia.<br> Servidora Pública.<br>Mulher. <br>casada,sem filhos. <br>Mora na zona sul da cidade, afastada de seu emprego.
Foi inserido a sigla dos estados nas outras três personas

2022-11-28 00:09 UTC, luciano-freitas-melo commented
- Feita as correções, algumas coisas foram alteradas de forma diferente. (descrito nos comentários de cada review)
- Foi alterado o formato das **bibliografias** para ficar de acordo com as normas abnt.

2022-11-28 12:08 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Descrição**       | Juliana Almeida, idade de 38 anos, moradora de Brasília-DF.<br> Enfermeira.<br>Mulher. <br>Solteira, devido longos períodos em trabalho no hospital não possui uma vida social
Asa sul é um bairro, creio que não precise falar que é da cidade.

2022-11-28 12:11 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +&emsp;&emsp;Os membros, Lucas Felipe e Luciano Freitas foram os responsaveis por criar personas que retratariam os usuarios mais comuns do Google Maps. A partir desses requisitos e da pesquisa de gru
Troque "`Os membros, Lucas Felipe e Luciano Freitas foram os responsaveis por criar personas [...]`" por "`Foram criadas personas [...]`", seja impessoal.

2022-11-28 12:13 UTC, marcusmartinss requested changes
Existem novas alterações a serem feitas.

2022-11-28 12:16 UTC, marcusmartinss commented on docs/elicitacao/personas.md
> +| **Objetivos**       | Juliana sempre foi uma pessoa muita ativa e focada em seu serviço, dévido sua devoção ao trabalho basicamente cumpre sempre a mesma rota do hospital para casa. Buscando ao máx
Não, mas o verbo `devido` se refere à `devoção`, não `sua`.

2022-11-28 12:27 UTC, marcusmartinss approved these changes
Tudo certo!

2022-11-28 12:28 UTC, merged