Criterios de aceitacao
Requisitos-de-Software/2022.2-GoogleMaps pull request #88
Opened 2023-01-02 18:03 UTC by marcusmartinss

2023-01-02 20:16 UTC, lucasfs1007 requested changes

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Os nomes das localizações devem estar visíveis no mapa de acordo com a escala. </br> 2. Quando a escala for maior que certa localização, ela não deve ser mostrada, a não
acho válido citar que "casa" e "trabalho" são endereços pinados no mapa porque fica de difícil entendimento para quem não conhece a plataforma.

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve haver mais de uma forma para se chegar a um local em um mesmo meio de transporte.                                                            |
não entendi o mesmo meio de transporte para esse critério de aceitação...seria mais de uma rota para transportes diferentes não ?

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível, como acessar as fotos na página do estabelecimento. </br> 2. Como usuário ou estabelecimento, deve ser possível adicionar fotos a página correspondent
A regra 5 já engloba a regra 4...eu removeria a 4 para evitar redundância e ajustava as numerações

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível inserir comentários na seção de avaliação dos estabelecimentos. </br> 2. Deve ser possível comentar outros comentários. |
acho que se colocar "deve ser possível responder outros comentários" fica melhor a coesão.

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível ver a faixa de preço dos produtos ou serviços de um estabelecimento pela quantidade sua de cifrões. </br> 2. A quantidade de cifrões deve se basear em
"serviços de um estabelecimento pela quantidade sua de cifrões." acho que a escrita "por sua quantidade de cifrões" fica melhor a coesão.

2023-01-02 20:16 UTC, lucasfs1007 commented on docs/modelagem/5.historias_usuario.md
> +| 30/12/2022 | 2.0    | Adição de critérios de aceitação das US 1 a 16 e 34 a 38  | Marcus    |             |
faltou meu nome como revisor nas modificações feitas no dia 30/12

2023-01-02 21:53 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Os nomes das localizações devem estar visíveis no mapa de acordo com a escala. </br> 2. Quando a escala for maior que certa localização, ela não deve ser mostrada, a não
É bom colocar em outro lugar, acho que nos critérios de aceitação não é um bom local pra colocar.

2023-01-02 21:55 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve haver mais de uma forma para se chegar a um local em um mesmo meio de transporte.                                                            |
Isso! Por exemplo, pegar dois ônibus para chegar em um lugar, ou apenas um, ou ir de metrô, ou ter aqueles caminhos alternativos com tempo maior (quando se está de carro).

2023-01-02 21:57 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível inserir comentários na seção de avaliação dos estabelecimentos. </br> 2. Deve ser possível comentar outros comentários. |
Feito!

2023-01-02 21:58 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível ver a faixa de preço dos produtos ou serviços de um estabelecimento pela quantidade sua de cifrões. </br> 2. A quantidade de cifrões deve se basear em
Concordo, feito!

2023-01-02 21:58 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| 30/12/2022 | 2.0    | Adição de critérios de aceitação das US 1 a 16 e 34 a 38  | Marcus    |             |
Verdade, vou alterar!

2023-01-02 22:02 UTC, marcusmartinss commented on docs/modelagem/5.historias_usuario.md
> +| Critérios de Aceitação | 1. Deve ser possível, como acessar as fotos na página do estabelecimento. </br> 2. Como usuário ou estabelecimento, deve ser possível adicionar fotos a página correspondent
Corrigido!

2023-01-03 00:06 UTC, lucasfs1007 approved these changes

2023-01-03 00:28 UTC, merged